<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<OutputPath>..\build\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<PropertyGroup>
		<Version>3.2.1</Version>
		<FileVersion>3.2.1.0</FileVersion>
		<AssemblyVersion>3.2.1.0</AssemblyVersion>
		<InformationalVersion>3.2.1</InformationalVersion>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="TShock" Version="5.2.3" />
	</ItemGroup>
</Project>
